apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wp-{{ .Values.name }}
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
    tier: frontend
    track: stable
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: wp-{{ .Values.name }}
      name: wp-nginx
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: wp-nginx
        app: wp-{{ .Values.name }}
        tier: frontend
        track: stable
    spec:
      containers:
      - image: {{ .Values.wpImage }}:{{ .Values.wpImageTag }}
        imagePullPolicy: IfNotPresent
        name: wp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: WP_CACHE_KEY_SALT
          value: {{ .Values.name }}
        - name: WP_REDIS_CLIENT
          value: "pecl"
        - name: WP_REDIS_SCHEME
          value: "tcp"
        - name: WP_REDIS_HOST
          value: {{ .Values.wpRedisHost }}
        - name: WP_REDIS_PORT
          value: {{ .Values.wpRedisPort | quote }}
        - name: WP_MEMORY_LIMIT
          value: {{ .Values.wpMemoryLimit }}
        - name: WP_MAX_MEMORY_LIMIT
          value: {{ .Values.wpMaxMemoryLimit }}
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_NAME
          value: wp_{{ .Values.name | replace "-" "_" }}
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        {{- if eq .Values.enableResourceLimits true }}
        resources:
          requests:
            memory: {{ .Values.requestsMemory | quote }}
            cpu: {{ .Values.requestsCpu | quote }}
          limits:
            memory: {{ .Values.limitsMemory | quote }}
            cpu: {{ .Values.limitsCpu | quote }}
        {{- end}}
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: php
          mountPath: /usr/local/etc/php/conf.d
        - name: cache
          mountPath: /var/run/nginx-cache
      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances={{ .Values.dbConn }}=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
      - image: {{ .Values.ngImage }}:{{ .Values.ngImageTag }}
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf-d
          mountPath: /etc/nginx-conf/conf.d
        - name: nginx-global
          mountPath: /etc/nginx-conf/global
        - name: nginx-html
          mountPath: /etc/nginx-conf/html
        - name: cache
          mountPath: /var/run/nginx-cache
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-{{ .Values.name }}-pv-claim
      - name: php
        configMap:
          name: php
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: nginx-global
        configMap:
          name: nginx-global
      - name: nginx-html
        configMap:
          name: nginx-html
      - name: cache
        emptyDir:
          medium: "Memory"
